name: Run Playwright

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        python-version: [3.9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install 
          pip install -r requirements.txt 
          pip install pytest-xdist
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      - name: Run Playwright tests with xvfb
        run: |
          source .venv/bin/activate  
          xvfb-run pytest tests/test_analytics_cookies.py -n 3