name: Run Playwright

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        python-version: [3.9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv .venv  # Create virtual environment
          source .venv/bin/activate  # Activate the virtual environment
          pip install -r requirements.txt  # Install dependencies
          pip install pytest-xdist  # Install pytest-xdist for parallel test execution
          python -m playwright install  # Install Playwright browsers

      - name: Install missing dependencies for WebKit (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y 
            libgtk-4-1 
            libgraphene-1.0-0 
            libvpx5 
            libopus0 
            libevent-2.1-7 
            libflite1 
            libgst1.0-0 
            libgdk-pixbuf2.0-0 
            libsecret-1-0 
            libavif16 
            libharfbuzz-icu0 
            libhyphen0 
            libmanette-0.2-0 
            libglesv2.2 
            libx264 
            libx11-dev 
            libvulkan1 
            liblcms2-2
          sudo add-apt-repository ppa:jonathonf/ffmpeg-4
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          sudo apt-get install -y libx264
          sudo apt-get install -y libgst-plugins-base1.0-0 libgst-plugins-good1.0-0 libgst-plugins-bad1.0-0
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev

      - name: Install xvfb for headless browser
        run: |
          sudo apt-get install -y xvfb

      - name: Run Playwright tests with xvfb
        run: |
          source .venv/bin/activate  
          xvfb-run pytest tests/test_analytics_cookies.py -n 3