name: Run Playwright

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        python-version: [3.9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv .venv  # Create virtual environment
          source .venv/bin/activate  # Activate the virtual environment
          pip install -r requirements.txt  # Install dependencies
          pip install pytest-xdist  # Install pytest-xdist for parallel test execution
          python -m playwright install  # Install Playwright browsers

      - name: Run Playwright tests
        run: |
          source .venv/bin/activate  # Activate virtual environment
          pytest tests/test_analytics_cookies.py -n 3  # Run tests in parallel with 3 workers