name: Run Playwright
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        python-version: [3.9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv .venv  
          source .venv/bin/activate  
          pip install -r requirements.txt 
          python -m playwright install  

      - name: Run Playwright tests
        run: |
          source .venv/bin/activate  # Aktywujemy środowisko
          pytest tests/test_analytics_cookies.py --browser ${{ matrix.browser }} -n 3 
